# Packaged data mirror — schemas, ontology, and presets.
# This directory is auto-generated by tools/sync_packaged_data_mirror.py.
# Do not edit files here directly; edit the repo-root originals instead.
