from __future__ import annotations

import re
import unittest
from pathlib import Path

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
ISSUE_ID_PATTERN = re.compile(r"""["'](ISSUE\.[A-Z0-9_]+(?:\.[A-Z0-9_]+)+)["']""")
SCAN_ROOTS = (
    REPO_ROOT / "src",
    REPO_ROOT / "tests",
    REPO_ROOT / "gui" / "desktop-tauri" / "src",
    REPO_ROOT / "gui" / "desktop-tauri" / "tests",
)
SCAN_SUFFIXES = {".js", ".py", ".ts", ".tsx"}

# Temporary migration baseline captured on 2026-03-23. New undeclared ISSUE.*
# IDs should be registered in ontology/issues.yaml rather than added here.
MIGRATION_ALLOWLIST = {
    "ISSUE.CLIP.TRUE_PEAK",
    "ISSUE.DOWNMIX.QA.CORRELATION_NON_MEASURABLE",
    "ISSUE.DOWNMIX.QA.SIMILARITY_GATE_FAILED",
    "ISSUE.DOWNMIX.QA.SIMILARITY_NON_MEASURABLE",
    "ISSUE.EVENT_LOG.INVALID_JSON",
    "ISSUE.EVENT_LOG.NOT_OBJECT",
    "ISSUE.EVENT_LOG.SCHEMA_INVALID",
    "ISSUE.FORMAT.LOSSY",
    "ISSUE.RENDER.ALL_MASTERS_INVALID",
    "ISSUE.RENDER.COMPAT.PLAN_JOB_COUNT_MISMATCH",
    "ISSUE.RENDER.COMPAT.PLAN_REPORT_JOB_SET_MISMATCH",
    "ISSUE.RENDER.COMPAT.PLAN_REPORT_LAYOUT_ID_MISMATCH",
    "ISSUE.RENDER.COMPAT.PLAN_REPORT_LINK_MISMATCH",
    "ISSUE.RENDER.COMPAT.PLAN_REPORT_PLAN_ID_MISMATCH",
    "ISSUE.RENDER.COMPAT.PLAN_REPORT_RESOLVED_TARGET_MISMATCH",
    "ISSUE.RENDER.COMPAT.PLAN_REPORT_RESOLVED_TARGET_MISSING",
    "ISSUE.RENDER.COMPAT.PLAN_REQUEST_MISSING",
    "ISSUE.RENDER.COMPAT.PLAN_REQUEST_ROUTING_PATH_MISMATCH",
    "ISSUE.RENDER.COMPAT.PLAN_REQUEST_SCENE_PATH_MISMATCH",
    "ISSUE.RENDER.COMPAT.PLAN_REQUEST_TARGETS_MISMATCH",
    "ISSUE.RENDER.PREFLIGHT.INPUT_MISSING",
    "ISSUE.RENDER.PREFLIGHT.INPUT_NOT_FILE",
    "ISSUE.RENDER.QA.CLIPPING",
    "ISSUE.RENDER.QA.CLIPPING_DETECTED",
    "ISSUE.RENDER.QA.CORRELATION_LOW",
    "ISSUE.RENDER.QA.CORRELATION_NON_MEASURABLE",
    "ISSUE.RENDER.QA.LOUDNESS_NON_MEASURABLE",
    "ISSUE.RENDER.QA.LRA_EXCESSIVE",
    "ISSUE.RENDER.QA.LRA_HIGH",
    "ISSUE.RENDER.QA.LRA_LOW",
    "ISSUE.RENDER.QA.PEAK_NON_MEASURABLE",
    "ISSUE.RENDER.QA.PLUGIN_DELTA_CREST_EXCESSIVE",
    "ISSUE.RENDER.QA.PLUGIN_DELTA_CREST_HIGH",
    "ISSUE.RENDER.QA.PLUGIN_DELTA_LUFS_EXCESSIVE",
    "ISSUE.RENDER.QA.PLUGIN_DELTA_LUFS_HIGH",
    "ISSUE.RENDER.QA.POLARITY_RISK",
    "ISSUE.RENDER.QA.SILENT_OUTPUT",
    "ISSUE.RENDER.QA.TEST",
    "ISSUE.RENDER.QA.TRUE_PEAK_EXCESSIVE",
    "ISSUE.RENDER.QA.TRUE_PEAK_HIGH",
    "ISSUE.RENDER.QA.TRUE_PEAK_WARN",
    "ISSUE.RENDER.RUN.DECODE_FAILED",
    "ISSUE.RENDER.RUN.DOWNMIX_SCOPE_UNSUPPORTED",
    "ISSUE.RENDER.RUN.ENCODE_FAILED",
    "ISSUE.RENDER.RUN.FFMPEG_REQUIRED",
    "ISSUE.RENDER.RUN.MIX_INPUT_SAMPLE_RATE_MISMATCH",
    "ISSUE.RENDER.RUN.OPTION_UNSUPPORTED",
    "ISSUE.RENDER.RUN.OUTPUT_FORMAT_UNSUPPORTED",
    "ISSUE.RENDER.RUN.PLUGIN_CHAIN_INVALID",
    "ISSUE.RENDER.RUN.PLUGIN_SOURCE_FORMAT_UNSUPPORTED",
    "ISSUE.RENDER.RUN.SOURCE_COUNT_UNSUPPORTED",
    "ISSUE.RENDER.RUN.SOURCE_FORMAT_UNSUPPORTED",
    "ISSUE.RENDER.RUN.SOURCE_LAYOUT_UNSUPPORTED",
    "ISSUE.RENDER.RUN.SOURCE_MISSING",
    "ISSUE.RENDER.RUN.SOURCE_STEMS_DIR_INVALID",
    "ISSUE.SCENE.INTENT.INVALID",
    "ISSUE.SCENE_LINT.CRITICAL_ANCHOR_LOW_CONFIDENCE",
    "ISSUE.SCENE_LINT.DUPLICATE_BUS_REFERENCE",
    "ISSUE.SCENE_LINT.DUPLICATE_OBJECT_REFERENCE",
    "ISSUE.SCENE_LINT.HEIGHT_SEND_CAPPED_TO_ZERO",
    "ISSUE.SCENE_LINT.IMMERSIVE_LOW_CONFIDENCE",
    "ISSUE.SCENE_LINT.IMMERSIVE_NO_BED_OR_AMBIENT",
    "ISSUE.SCENE_LINT.IMMERSIVE_TEMPLATE_MISSING",
    "ISSUE.SCENE_LINT.LOCK_CONFLICT",
    "ISSUE.SCENE_LINT.LOCK_CONTEXT_MISSING",
    "ISSUE.SCENE_LINT.LOCK_OVERRIDE_BUS_ASSUMPTION_MISSING",
    "ISSUE.SCENE_LINT.LOCK_OVERRIDE_ROLE_UNKNOWN",
    "ISSUE.SCENE_LINT.LOCK_SCOPE_CONFLICT",
    "ISSUE.SCENE_LINT.LOCK_UNKNOWN",
    "ISSUE.SCENE_LINT.MISSING_STEM_FILE",
    "ISSUE.SCENE_LINT.MISSING_STEM_ID",
    "ISSUE.SCENE_LINT.MISSING_STEM_REFERENCE",
    "ISSUE.SCENE_LINT.OUT_OF_RANGE_AZIMUTH",
    "ISSUE.SCENE_LINT.OUT_OF_RANGE_DEPTH",
    "ISSUE.SCENE_LINT.OUT_OF_RANGE_WIDTH",
    "ISSUE.SEMANTICS.BED_ONLY_OBJECT_CONFLICT",
    "ISSUE.SEMANTICS.CHANNEL_MODE_INVALID",
    "ISSUE.SEMANTICS.LATENCY_FIXED_MISSING_SAMPLES",
    "ISSUE.SEMANTICS.LATENCY_TYPE_INVALID",
    "ISSUE.SEMANTICS.LAYOUT_SAFETY_INVALID",
    "ISSUE.SEMANTICS.LAYOUT_SPECIFIC_NO_LAYOUT",
    "ISSUE.SEMANTICS.LINK_GROUPS_INVALID",
    "ISSUE.SEMANTICS.LINK_GROUPS_REQUIRES_LINKED_MODE",
    "ISSUE.SEMANTICS.PURITY_RANDOMNESS_CONFLICT",
    "ISSUE.SEMANTICS.SCENE_SCOPE_INVALID",
    "ISSUE.SEMANTICS.SCENE_SCOPE_OBJECT_CONFLICT",
    "ISSUE.SEMANTICS.SEED_POLICY_INVALID",
    "ISSUE.SEMANTICS.SPEAKER_POSITIONS_NO_LAYOUT",
    "ISSUE.TONE.RESHAPE",
    "ISSUE.UI.LAYOUT.MIN_SIZE_BROKEN",
    "ISSUE.UI.LAYOUT.OFF_SCREEN",
    "ISSUE.UI.LAYOUT.OVERLAP",
    "ISSUE.UI.PLUGIN.CONFIG_SCHEMA_INVALID",
    "ISSUE.UI.PLUGIN.CONFIG_SCHEMA_REQUIRED",
    "ISSUE.UI.PLUGIN.HINT_PARAM_REF_UNKNOWN",
    "ISSUE.UI.PLUGIN.HINT_SCHEMA_INVALID",
    "ISSUE.UI.PLUGIN.LAYOUT_FIELD_INVALID",
    "ISSUE.UI.PLUGIN.LAYOUT_LOAD_FAILED",
    "ISSUE.UI.PLUGIN.LAYOUT_PARAM_HINT_MISSING",
    "ISSUE.UI.PLUGIN.LAYOUT_SCHEMA_INVALID",
    "ISSUE.UI.PLUGIN.LAYOUT_SNAPSHOT_INVALID",
    "ISSUE.UI.PLUGIN.LAYOUT_VIOLATION",
    "ISSUE.UI.PLUGIN.WIDGET_PARAM_REF_AMBIGUOUS",
    "ISSUE.UI.PLUGIN.WIDGET_PARAM_REF_REQUIRED",
    "ISSUE.UI.PLUGIN.WIDGET_PARAM_REF_UNKNOWN",
    "ISSUE.VALIDATION.SCENE_INTENT_ENUM_INVALID",
    "ISSUE.VALIDATION.SCENE_INTENT_PARAM_OUT_OF_RANGE",
    "ISSUE.VALIDATION.SCENE_INTENT_PARAM_TYPE_INVALID",
    "ISSUE.VALIDATION.SCENE_INTENT_PARAM_UNKNOWN",
}


def _scan_issue_ids() -> set[str]:
    found: set[str] = set()
    for root in SCAN_ROOTS:
        for path in root.rglob("*"):
            if path.suffix not in SCAN_SUFFIXES:
                continue
            text = path.read_text(encoding="utf-8")
            found.update(ISSUE_ID_PATTERN.findall(text))
    return found


def _load_registered_issue_ids() -> set[str]:
    payload = yaml.safe_load((REPO_ROOT / "ontology" / "issues.yaml").read_text(encoding="utf-8"))
    issues = payload.get("issues", {})
    return {issue_id for issue_id in issues if issue_id.startswith("ISSUE.")}


class TestIssueRegistryEnforcement(unittest.TestCase):
    def test_repo_issue_ids_are_registered_or_allowlisted(self) -> None:
        found_issue_ids = _scan_issue_ids()
        registered_issue_ids = _load_registered_issue_ids()
        unknown_issue_ids = found_issue_ids - registered_issue_ids

        added_ids = sorted(unknown_issue_ids - MIGRATION_ALLOWLIST)
        stale_allowlist_ids = sorted(MIGRATION_ALLOWLIST - unknown_issue_ids)

        message_parts: list[str] = []
        if added_ids:
            message_parts.append(
                "Register new ISSUE.* IDs in ontology/issues.yaml instead of adding"
                f" them ad hoc: {', '.join(added_ids)}"
            )
        if stale_allowlist_ids:
            message_parts.append(
                "Remove stale IDs from MIGRATION_ALLOWLIST because they are now"
                f" registered or unused: {', '.join(stale_allowlist_ids)}"
            )

        self.assertFalse(message_parts, " ".join(message_parts))
