"""Canonical backend status vocabularies.

These constants freeze meaning at the backend layer. Presentation layers must
map from these values rather than inventing synonyms inline.
"""

from __future__ import annotations

# Lifecycle statuses: long-running workflow outcomes such as safe-render
# receipts. Keep separate from deliverable validity and QA gate semantics.
LIFECYCLE_STATUS_DRY_RUN_ONLY = "dry_run_only"
LIFECYCLE_STATUS_COMPLETED = "completed"
LIFECYCLE_STATUS_BLOCKED = "blocked"
LIFECYCLE_STATUSES = (
    LIFECYCLE_STATUS_DRY_RUN_ONLY,
    LIFECYCLE_STATUS_COMPLETED,
    LIFECYCLE_STATUS_BLOCKED,
)

# Deliverable execution statuses: machine-readable state of one deliverable.
DELIVERABLE_STATUS_SUCCESS = "success"
DELIVERABLE_STATUS_FAILED = "failed"
DELIVERABLE_STATUS_PARTIAL = "partial"
DELIVERABLE_STATUS_INVALID_MASTER = "invalid_master"
DELIVERABLE_STATUSES = (
    DELIVERABLE_STATUS_SUCCESS,
    DELIVERABLE_STATUS_FAILED,
    DELIVERABLE_STATUS_PARTIAL,
    DELIVERABLE_STATUS_INVALID_MASTER,
)

# Deliverable validity/result buckets: roll-up classification for master
# validity and mixed deliverable outcomes.
DELIVERABLE_RESULT_BUCKET_VALID_MASTER = "valid_master"
DELIVERABLE_RESULT_BUCKET_SUCCESS_NO_MASTER = "success_no_master"
DELIVERABLE_RESULT_BUCKET_PARTIAL_SUCCESS = "partial_success"
DELIVERABLE_RESULT_BUCKET_DIAGNOSTICS_ONLY = "diagnostics_only"
DELIVERABLE_RESULT_BUCKET_FULL_FAILURE = "full_failure"
DELIVERABLE_RESULT_BUCKETS = (
    DELIVERABLE_RESULT_BUCKET_VALID_MASTER,
    DELIVERABLE_RESULT_BUCKET_SUCCESS_NO_MASTER,
    DELIVERABLE_RESULT_BUCKET_PARTIAL_SUCCESS,
    DELIVERABLE_RESULT_BUCKET_DIAGNOSTICS_ONLY,
    DELIVERABLE_RESULT_BUCKET_FULL_FAILURE,
)

# QA gate statuses: explicit gate/evaluation outcomes, not workflow lifecycle.
QA_GATE_STATUS_PASS = "pass"
QA_GATE_STATUS_WARN = "warn"
QA_GATE_STATUS_FAIL = "fail"
QA_GATE_STATUS_NOT_RUN = "not_run"
QA_GATE_STATUSES = (
    QA_GATE_STATUS_PASS,
    QA_GATE_STATUS_WARN,
    QA_GATE_STATUS_FAIL,
    QA_GATE_STATUS_NOT_RUN,
)

# Measurement states: whether a QA metric was applicable and measurable.
MEASUREMENT_STATE_MEASURED = "measured"
MEASUREMENT_STATE_NOT_APPLICABLE = "not_applicable"
MEASUREMENT_STATE_FAILED = "measurement_failed"
MEASUREMENT_STATE_INVALID_DUE_TO_SILENCE = "invalid_due_to_silence"
MEASUREMENT_STATES = (
    MEASUREMENT_STATE_MEASURED,
    MEASUREMENT_STATE_NOT_APPLICABLE,
    MEASUREMENT_STATE_FAILED,
    MEASUREMENT_STATE_INVALID_DUE_TO_SILENCE,
)

__all__ = [
    "DELIVERABLE_RESULT_BUCKET_DIAGNOSTICS_ONLY",
    "DELIVERABLE_RESULT_BUCKET_FULL_FAILURE",
    "DELIVERABLE_RESULT_BUCKET_PARTIAL_SUCCESS",
    "DELIVERABLE_RESULT_BUCKET_SUCCESS_NO_MASTER",
    "DELIVERABLE_RESULT_BUCKET_VALID_MASTER",
    "DELIVERABLE_RESULT_BUCKETS",
    "DELIVERABLE_STATUSES",
    "DELIVERABLE_STATUS_FAILED",
    "DELIVERABLE_STATUS_INVALID_MASTER",
    "DELIVERABLE_STATUS_PARTIAL",
    "DELIVERABLE_STATUS_SUCCESS",
    "LIFECYCLE_STATUSES",
    "LIFECYCLE_STATUS_BLOCKED",
    "LIFECYCLE_STATUS_COMPLETED",
    "LIFECYCLE_STATUS_DRY_RUN_ONLY",
    "MEASUREMENT_STATES",
    "MEASUREMENT_STATE_FAILED",
    "MEASUREMENT_STATE_INVALID_DUE_TO_SILENCE",
    "MEASUREMENT_STATE_MEASURED",
    "MEASUREMENT_STATE_NOT_APPLICABLE",
    "QA_GATE_STATUSES",
    "QA_GATE_STATUS_FAIL",
    "QA_GATE_STATUS_NOT_RUN",
    "QA_GATE_STATUS_PASS",
    "QA_GATE_STATUS_WARN",
]
